### ISSUE TITLE
aws.yaml

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh.aws#2]
instead of using aws.yaml please define it in ~/.cloudmesh/cloudmesh.yaml

you can use ConfigDict 

or from ruaml import yaml and use yaml.load

**Comment by MilindSuryawanshi** [comment]
Done, now fetching the information from cloudmesh.yaml

**Comment by laszewsk** [comment]
great. but i see some inconsistency in documentation, so i filed it aagin
