### ISSUE TITLE
no png for verbatim stuff

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh.aws#5]
there are lots of unnecessary images/png, instead we need to use verbatim in figures. See bellow
 
\begin{figure}[htb]
  \centering
  \begin{verbatim}
  set default cloud=aws
  vm boot
  set default cloud=openstack
  vm boot 
  \end{verbatim}
  \vspace{-2.0\baselineskip}
  \caption{cms aws image refresh}
  \label{fig:imagerefresh}
\end{figure}

**Comment by MilindSuryawanshi** [comment]
Removed the images and replaced the actual tables.
